      BETH/USDT, 
      BICO/USDT,
      BIFI/USDT, 
      BKRW/USDT, 
      BLUR/USDT, 
       BLZ/USDT, 
       BNB/USDT, 
   BNBBEAR/USDT, 
   BNBBULL/USDT, 
   BNBDOWN/USDT, 
     BNBUP/USDT, 
       BNT/USDT, 
       BNX/USDT, 
      BOND/USDT, 
       BSV/USDT, 
       BSW/USDT, 
       BTC/USDT, 
   BTCDOWN/USDT, 
     BTCST/USDT, 
     BTCUP/USDT, 
       BTG/USDT, 
       BTS/USDT, 
       BTT/USDT, 
      BTTC/USDT 
      BULL/USDT 
    BURGER/USDT 
      BUSD/USDT 
      BZRX/USDT 
       C98/USDT 
      CAKE/USDT 
      CELO/USDT 
      CELR/USDT 
       CFX/USDT 
     CHESS/USDT 
       CHR/USDT 
       CHZ/USDT 
      CITY/USDT 
       CKB/USDT 
       CLV/USDT 
     COCOS/USDT 
     COMBO/USDT 
      COMP/USDT 
       COS/USDT 
      COTI/USDT 
     CREAM/USDT 
       CRV/USDT 
       CTK/USDT 
      CTSI/USDT 
      CTXC/USDT 
       CVC/USDT 
       CVP/USDT 
       CVX/USDT 
     CYBER/USDT 
       DAI/USDT 
       DAR/USDT 
      DASH/USDT 
      DATA/USDT 
       DCR/USDT 
      DEGO/USDT 
      DENT/USDT 
      DEXE/USDT 
        DF/USDT 
       DGB/USDT 
       DIA/USDT 
       DNT/USDT 
      DOCK/USDT 
      DODO/USDT 
      DOGE/USDT 
       DOT/USDT 
   DOTDOWN/USDT 
     DOTUP/USDT 
      DREP/USDT 
      DUSK/USDT 
      DYDX/USDT 
       EDU/USDT 
      EGLD/USDT 
       ELF/USDT 
       ENJ/USDT 
       ENS/USDT 
       EOS/USDT 
   EOSBEAR/USDT 
   EOSBULL/USDT 
   EOSDOWN/USDT 
     EOSUP/USDT 
       EPS/USDT 
       EPX/USDT 
       ERD/USDT 
       ERN/USDT 
       ETC/USDT 
       ETH/USDT 
   ETHBEAR/USDT 
   ETHBULL/USDT 
   ETHDOWN/USDT 
     ETHUP/USDT 
       EUR/USDT 
      FARM/USDT 
     FDUSD/USDT 
       FET/USDT 
      FIDA/USDT 
       FIL/USDT 
   FILDOWN/USDT 
     FILUP/USDT 
       FIO/USDT 
      FIRO/USDT 
       FIS/USDT 
       FLM/USDT 
     FLOKI/USDT 
      FLOW/USDT 
      FLUX/USDT 
       FOR/USDT 
     FORTH/USDT 
     FRONT/USDT 
       FTM/USDT 
       FTT/USDT 
       FUN/USDT 
       FXS/USDT 
       GAL/USDT 
      GALA/USDT 
       GAS/USDT 
       GBP/USDT 
       GFT/USDT 
      GHST/USDT 
       GLM/USDT 
      GLMR/USDT 
       GMT/USDT 
       GMX/USDT 
       GNO/USDT 
       GNS/USDT 
       GRT/USDT 
       GTC/USDT 
       GTO/USDT 
       GXS/USDT 
      HARD/USDT 
      HBAR/USDT 
        HC/USDT 
       HFT/USDT 
      HIFI/USDT 
      HIGH/USDT 
      HIVE/USDT 
       HNT/USDT 
      HOOK/USDT 
       HOT/USDT 
       ICP/USDT 
       ICX/USDT 
        ID/USDT 
      IDEX/USDT 
       ILV/USDT 
       IMX/USDT 
       INJ/USDT 
      IOST/USDT 
      IOTA/USDT 
      IOTX/USDT 
        IQ/USDT 
      IRIS/USDT 
     JASMY/USDT 
       JOE/USDT 
       JST/USDT 
       JTO/USDT 
       JUV/USDT 
      KAVA/USDT 
       KDA/USDT 
      KEEP/USDT 
       KEY/USDT 
      KLAY/USDT 
       KMD/USDT 
       KNC/USDT 
      KP3R/USDT 
       KSM/USDT 
     LAZIO/USDT 
       LDO/USDT 
      LEND/USDT 
     LEVER/USDT 
      LINA/USDT 
      LINK/USDT 
  LINKDOWN/USDT 
    LINKUP/USDT 
       LIT/USDT 
      LOKA/USDT 
      LOOM/USDT 
       LPT/USDT 
      LQTY/USDT 
       LRC/USDT 
       LSK/USDT 
       LTC/USDT 
   LTCDOWN/USDT 
     LTCUP/USDT 
       LTO/USDT 
      LUNA/USDT 
      LUNC/USDT 
     MAGIC/USDT 
      MANA/USDT 
      MASK/USDT 
     MATIC/USDT 
       MAV/USDT 
       MBL/USDT 
      MBOX/USDT 
        MC/USDT 
       MCO/USDT 
       MDT/USDT 
       MDX/USDT 
      MEME/USDT 
       MFT/USDT 
      MINA/USDT 
       MIR/USDT 
      MITH/USDT 
       MKR/USDT 
       MLN/USDT 
       MOB/USDT 
      MOVR/USDT 
       MTL/USDT 
     MULTI/USDT 
      NANO/USDT 
       NBS/USDT 
      NEAR/USDT 
      NEBL/USDT 
       NEO/USDT 
      NEXO/USDT 
       NKN/USDT 
       NMR/USDT 
      NPXS/USDT 
      NTRN/USDT 
        NU/USDT 
      NULS/USDT 
       OAX/USDT 
     OCEAN/USDT 
        OG/USDT 
       OGN/USDT 
        OM/USDT 
       OMG/USDT 
       ONE/USDT 
       ONG/USDT 
       ONT/USDT 
      OOKI/USDT 
        OP/USDT 
      ORDI/USDT 
       ORN/USDT 
      OSMO/USDT 
       OXT/USDT 
       PAX/USDT 
      PAXG/USDT 
    PENDLE/USDT 
    PEOPLE/USDT 
      PEPE/USDT 
      PERL/USDT 
      PERP/USDT 
       PHA/USDT 
       PHB/USDT 
      PIVX/USDT 
       PLA/USDT 
       PNT/USDT 
      POLS/USDT 
      POLY/USDT 
     POLYX/USDT 
      POND/USDT 
     PORTO/USDT 
      POWR/USDT 
      PROM/USDT 
      PROS/USDT 
       PSG/USDT 
    PUNDIX/USDT 
       PYR/USDT 
        QI/USDT 
       QKC/USDT 
       QNT/USDT 
      QTUM/USDT 
     QUICK/USDT 
       RAD/USDT 
      RAMP/USDT 
      RARE/USDT 
       RAY/USDT 
      RDNT/USDT 
      REEF/USDT 
       REI/USDT 
       REN/USDT 
       REP/USDT 
       REQ/USDT 
       RGT/USDT 
       RIF/USDT 
       RLC/USDT 
      RNDR/USDT 
      ROSE/USDT 
       RPL/USDT 
       RSR/USDT 
      RUNE/USDT 
       RVN/USDT 
      SAND/USDT 
    SANTOS/USDT 
        SC/USDT 
      SCRT/USDT 
       SEI/USDT 
       SFP/USDT 
      SHIB/USDT 
       SKL/USDT 
       SLP/USDT 
       SNT/USDT 
       SNX/USDT 
       SOL/USDT 
     SPELL/USDT 
       SRM/USDT 
       SSV/USDT 
     STEEM/USDT 
       STG/USDT 
      STMX/USDT 
     STORJ/USDT 
     STORM/USDT 
      STPT/USDT 
     STRAT/USDT 
     STRAX/USDT 
       STX/USDT 
       SUI/USDT 
       SUN/USDT 
     SUPER/USDT 
      SUSD/USDT 
     SUSHI/USDT 
 SUSHIDOWN/USDT 
   SUSHIUP/USDT 
       SXP/USDT 
   SXPDOWN/USDT 
     SXPUP/USDT 
       SYN/USDT 
       SYS/USDT 
         T/USDT 
       TCT/USDT 
     TFUEL/USDT 
     THETA/USDT 
       TIA/USDT 
       TKO/USDT 
       TLM/USDT 
      TOMO/USDT 
      TORN/USDT 
       TRB/USDT 
     TRIBE/USDT 
      TROY/USDT 
       TRU/USDT 
       TRX/USDT 
   TRXDOWN/USDT 
     TRXUP/USDT 
      TUSD/USDT 
       TVK/USDT 
       TWT/USDT 
       UFT/USDT 
       UMA/USDT 
      UNFI/USDT 
       UNI/USDT 
   UNIDOWN/USDT 
     UNIUP/USDT 
      USDC/USDT 
      USDP/USDT 
      USDS/USDT 
     USDSB/USDT 
       UST/USDT 
      USTC/USDT 
       UTK/USDT 
     VANRY/USDT 
       VEN/USDT 
       VET/USDT 
       VGX/USDT 
       VIB/USDT 
       VIC/USDT 
      VIDT/USDT 
      VITE/USDT 
     VOXEL/USDT 
      VTHO/USDT 
       WAN/USDT 
     WAVES/USDT 
      WAXP/USDT 
     WBETH/USDT 
      WBTC/USDT 
       WIN/USDT 
      WING/USDT 
       WLD/USDT 
      WNXM/USDT 
       WOO/USDT 
       WRX/USDT 
       WTC/USDT 
       XEC/USDT 
       XEM/USDT 
       XLM/USDT 
   XLMDOWN/USDT 
     XLMUP/USDT 
       XMR/USDT 
       XNO/USDT 
       XRP/USDT 
   XRPBEAR/USDT 
   XRPBULL/USDT 
   XRPDOWN/USDT 
     XRPUP/USDT 
       XTZ/USDT 
   XTZDOWN/USDT 
     XTZUP/USDT 
       XVG/USDT 
       XVS/USDT 
       XZC/USDT 
       YFI/USDT 
   YFIDOWN/USDT 
      YFII/USDT 
     YFIUP/USDT 
       YGG/USDT 
       ZEC/USDT 
       ZEN/USDT 
       ZIL/USDT 
       ZRX/USDT 


            "NEAR/USDT","VET/USDT","API3/USDT","FTM/USDT",
            "BETA/USDT","CVX/USDT","ENS/USDT","REEF/USDT",
            "ACA/USDT","KDA/USDT","THETA/USDT","BIFI/USDT",
            "MATIC/USDT","AEUR/USDT","BTCUP/USDT","CTSI/USDT","DATA/USDT","ATA/USDT",
            "GNO/USDT","FIL/USDT","APT/USDT", "ID/USDT","GLMR/USDT", "GRT/USDT",
            "DENT/USDT","EOS/USDT","IOST/USDT","ONT/USDT","LINK/USDT","COTI/USDT","XRP/USDT",
            "BAL/USDT","SKL/USDT","AAVE/USDT","AVA/USDT","DASH/USDT","RLC/USDT","LOKA/USDT",
            "ANT/USDT","PUNDIX/USDT","KAVA/USDT","ADX/USDT","ERN/USDT", "GTC/USDT", "EGLD/USDT", "CAKE/USDT", 
            "PORTO/USDT", "STPT/USDT", "BNBDOWN/USDT", "ADA/USDT", "CHR/USDT", "PEOPLE/USDT","AUDIO/USDT",
            "CELO/USDT","IDEX/USDT","OM/USDT","POLYX/USDT", "PLA/USDT","CVP/USDT","NULS/USDT","GAL/USDT",
            "RAD/USDT","FXS/USDT","ANKR/USDT","UFT/USDT","PROS/USDT", 
            "DATA/USDT","MBL/USDT","MOB/USDT","ORDI/USDT","OCEAN/USDT",
            "CELR/USDT","JOE/USDT","CTK/USDT","FIRO/USDT","VITE/USDT", 
            "FIS/USDT","ALPACA/USDT","AXS/USDT","WAXP/USDT","ARPA/USDT", 
            "STG/USDT","AR/USDT","STMX/USDT","KLAY/USDT","PROM/USDT","PERP/USDT","GFT/USDT", 
            "NEO/USDT","JUV/USDT","SYN/USDT","DCR/USDT","GHST/USDT", 
            "MTL/USDT","STORJ/USDT","NKN/USDT","AMB/USDT","GLM/USDT","HIVE/USDT", 
            "FIO/USDT","1INCH/USDT","QKC/USDT","BADGER/USDT","FRONT/USDT", 
            "WING/USDT","UNFI/USDT","SUSHI/USDT","FOR/USDT","GAS/USDT","REN/USDT","FLM/USDT", 
            "REI/USDT","ALPHA/USDT","STRAX/USDT","PHB/USDT","EDU/USDT","LEVER/USDT", 
            "BAKE/USDT","ZRX/USDT","ONG/USDT","YGG/USDT","POWR/USDT","STEEM/USDT","BNT/USDT", 
            "MDT/USDT","LQTY/USDT","LUNA/USDT","AGLD/USDT","ARDR/USDT","HIFI/USDT" 
